apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-1-1-0
  namespace: canary-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: 1-1-0
  template:
    metadata:
      labels:
        app: hello
        version: 1-1-0
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        args:
          - "-text=version 1-1-0"
