apiVersion: v1
kind: Service
metadata:
  name: hello-lb
  namespace: canary-simple
spec:
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 5678
    protocol: TCP
    name: http
  type: LoadBalancer
